# Generated by Django 5.2.8 on 2025-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='제목 없음', max_length=200, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
