# Generated by Django 5.2.8 on 2025-11-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveBigIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
