# Generated by Django 5.2.8 on 2025-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board/images/%Y/%m/%d/', verbose_name='이미지'),
        ),
    ]
